- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: pull docker image
      shell: /usr/local/bin/docker pull chhajed7890/scientific_calculator

    - name: running container
      shell: /usr/local/bin/docker run -it -d -p 6000:6000 chhajed7890/scientific_calculator




